name: Gluckstaler
favicon: null
layout_spectrum: 0.60759
typography_spectrum: 0.13608153304085135
title: Ralph Lengler
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#81b9cc'
    - '#0f283e'
    - '#e53543'
    - '#eb8e2d'
  brandStrength: 0.75
  lightness: 0.5544032617472112
  saturation: 0.6928386790677905
  rhythmicContrast: 0.15160988504067063
purpose: []
