name: Gluckstaler
favicon: null
layout_spectrum: 1
typography_spectrum: 0.13608153304085135
title: Ralph Lengler
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#81adbc'
    - '#4c4c4c'
    - '#000000'
    - '#fc6a4f'
  brandStrength: 0.5
  lightness: 0.5544032617472112
  saturation: 0.6928386790677905
  rhythmicContrast: 0.5
purpose: []
